apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: hello
          image: 192.168.64.26:5000/myapp:v3
          imagePullPolicy: Always
