apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: hello-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: "300m"
          memory: "256Mi"

